name: Build and Release macos app

on:
  push:
    tags:
      - 'v*'
  workflow_call:
    secrets:
      CODE_SIGN_P12_BASE64:
        description: 'Base64 encoded P12 certificate'
        required: true
      CODE_SIGN_P12_PASSWORD:
        description: 'Password for the P12 certificate'
        required: true

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write  # Grant write permission to contents

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Build frontend
        run: DESTINATION=desktop yarn workspace interface build

      - name: Create certificate
        working-directory: apps/desktop
        run: |
          echo ${{ secrets.CODE_SIGN_P12_BASE64 }} | base64 --decode > myapp.p12

      - name: Debug Certificate
        working-directory: apps/desktop
        run: |
          echo "Certificate location check:"
          ls -la myapp.p12
          echo "Current directory:"
          pwd
          echo "Certificate file size:"
          stat -f %z myapp.p12

      - name: Build and Make
        working-directory: apps/desktop
        env:
          CSC_LINK: myapp.p12
          CSC_KEY_PASSWORD: ${{ secrets.CODE_SIGN_P12_PASSWORD }}
          DEBUG: electron-osx-sign*
        run: |
          yarn make --verbose


      - name: Debug Build Output
        working-directory: apps/desktop
        run: |
          echo "Listing out directory structure:"
          ls -R out/

          echo "\nFinding DMG files:"
          find . -name "*.dmg"

          echo "\nChecking make directory:"
          ls -la out/make/

      - name: Verify Signing
        working-directory: apps/desktop
        run: |
          DMG_PATH=$(find out/make -name "*.dmg")
          echo "Found DMG at: $DMG_PATH"

          if [ -f "$DMG_PATH" ]; then
            echo "Checking DMG signature..."
            codesign -vv --deep --strict "$DMG_PATH"

            echo "Checking app bundle signature..."
            APP_PATH=$(find out/make -name "*.app")
            codesign -vv --deep --strict "$APP_PATH"
          else
            echo "DMG file not found"
            exit 1
          fi

      - name: List built artifacts
        shell: bash
        run: |
          ls -R "${{ github.workspace }}/apps/desktop/out/make" || echo "No macOS artifacts found"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
           /Users/runner/work/ai-juicing-juicebox/ai-juicing-juicebox/apps/desktop/out/make/**.dmg
